# Generated by Django 4.2.11 on 2025-05-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='couleur',
            field=models.JSONField(default=list, help_text='Liste des couleurs disponibles'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='status',
            field=models.CharField(choices=[('verified', 'Vérifié'), ('unverified', 'Non vérifié')], default='unverified', max_length=20),
        ),
        migrations.AlterField(
            model_name='produit',
            name='tags',
            field=models.TextField(help_text='Séparer les tags par des virgules'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='taille',
            field=models.JSONField(default=list, help_text='Liste des tailles disponibles'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='status',
            field=models.CharField(choices=[('verified', 'Vérifié'), ('unverified', 'Non vérifié')], default='unverified', max_length=20),
        ),
    ]
